CREATE TABLE `EventCodeMapping` (
  `id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  `eventCode` VARCHAR(8) NOT NULL,
  `eventToken` VARCHAR(12) NOT NULL,
  `eventName` VARCHAR(255) NULL DEFAULT NULL,
  `createTime` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (`eventCode`, `eventToken`));
